### ISSUE TITLE
Feature: ability to include mp3 metadata in complete call

### ISSUE THREAD

**Issue by conor-mac-aoidh** [moviemasher/moviemasher.rb#3]
I noticed while running a job on an mp3 file that the metadata information is readily available (of course, only if there is metadata in the file). See extract from MM logs:

```
-async is forwarded to lavfi similarly to -af aresample=async=1:min_hard_comp=0.100000:first_pts=0.
Output #0, mp3, to '/tmp/moviemasher/temporary/2007c670-6765-0132-b56c-22000b5e8178/2008baa0-6765-0132-b572-22000b5e8178.mp3':
  Metadata:
    TPE1            : Jack Johnson
    TDRL            : 2001
    TCON            : Folk/Rock
    TIT2            : Inaudible Melodies
    TALB            : Brushfire Fairytales
    TRCK            : 1
    TSSE            : Lavf56.7.104
    Stream #0:0: Audio: mp3 (libmp3lame), 44100 Hz, stereo, s16p, 128 kb/s
    Metadata:
      encoder         : Lavc56.3.101 libmp3lame
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> mp3 (libmp3lame))
Press [q] to stop, [?] for help
size=    3367kB time=00:03:35.43 bitrate= 128.0kbits/s    
video:0kB audio:3367kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.017318%
```

It would be great if this data was parsed by MM and exposed via variables in the callback responses. Example syntax:

```javascript
{
   'title' : '{output.meta.title}',
   'year' : '{output.meta.year}',
   'genre' : '{output.meta.genre}',
   'artist' : '{output.meta.artist}',
   'album' : '{output.meta.album}'
}
```

Thanks

Conor

**Comment by conor-mac-aoidh** [comment]
This no longer seems to be working in the latest commit. I can see metadata in the moviemasher log, but inputs.0.metadata is never set in the complete callback.

Here is an example response from the moviemasher complete callback:

```javascript
# job.body.inputs[0]
{ 
   name: 'test-bucket/audio/14b4f00195e_14b9eaf8372/original.mp3',
   type: 'audio',
   source:
   {
     type: 'https',
     host: 's3.amazonaws.com',
     path: '/test-bucket/audio/14b4f00195e_14b9eaf8372/original.mp3',
     port: 443
   },
   offset: 0,
   start: 0,
   duration: 334.9,
   length: 334.9,
   base_source: null,
   module_source: null,
   effects: [],
   merger:{
      id: 'com.moviemasher.merger.default',
      type: 'merger',
      filters: [ [Object] ]
   },
   scaler:
    { id: 'com.moviemasher.scaler.default',
      type: 'scaler',
      filters: [ [Object], [Object] ] },
   gain: 1,
   loop: 1,
   no_video: true,
   no_audio: false,
   av: 'audio',
   input_url: 'https://s3.amazonaws.com:443/test-bucket//audio/14b4f00195e_14b9eaf8372/original.mp3',
   cached_file: '/tmp/moviemasher/download/ee7ce7628a2132958dd746b7c43935721658a219b84db5b519c8c17fb9c6c87f/downloaded.mp3',
   range: '#<MovieMasher::TimeRange:0x00000000ee9d00>'
}
```

And here is the metadata from the moviemasher logs:

```
Input #0, wav, from '/tmp/moviemasher/download/ee7ce7628a2132958dd746b7c43935721658a219b84db5b519c8c17fb9c6c87f/downloaded-intermediate.wav':
  Metadata:
    artist          : Red Hot Chili Peppers
    date            : 2006
    genre           : Other
    title           : Snow ((Hey Oh))
    album           : Stadium Arcadium Disc 1
    track           : 2
    encoder         : Lavf56.7.104
  Duration: 00:05:34.89, bitrate: 1411 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, 2 channels, s16, 1411 kb/s
-async is forwarded to lavfi similarly to -af aresample=async=1:min_hard_comp=0.100000:first_pts=0.
Output #0, mp3, to '/dev/null':
  Metadata:
    TPE1            : Red Hot Chili Peppers
    TDRL            : 2006
    TCON            : Other
    TIT2            : Snow ((Hey Oh))
    TALB            : Stadium Arcadium Disc 1
    TRCK            : 2
    TSSE            : Lavf56.7.104
    Stream #0:0: Audio: mp3 (libmp3lame), 44100 Hz, stereo, s16p, 128 kb/s
    Metadata:
      encoder         : Lavc56.3.101 libmp3lame
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_s16le (native) -> mp3 (libmp3lame))
```

Any idea what could be causing this?

**Comment by syntropo** [comment]
Yes, I noticed this was broken in the last push - sorry. It's fixed in the push I just made, though I'm not sure there aren't other regressions regarding the support being added for additional third party systems like SQS and S3. LMK if you run into any issues.

**Comment by conor-mac-aoidh** [comment]
Ok cool. I'm getting an error (from the error callback):

```
uninitialized constant MovieMasher::HttpDownloadService
```

**Comment by syntropo** [comment]
Hmm... weird - is this in docker? How are you loading the script?

**Comment by conor-mac-aoidh** [comment]
No, we are not using docker yet - but planning to move to it soon.

The script is just checked out from git, and run with cron. We are using S3 to store files, SQS to send jobs.

**Comment by conor-mac-aoidh** [comment]
In case this is helpful:

```
CAUGHT uninitialized constant MovieMasher::HttpDownloadService /home/ec2-user/moviemasher.rb/service/download/https.rb:3:in `<module:MovieMasher>'
/home/ec2-user/moviemasher.rb/service/download/https.rb:2:in `<top (required)>'
/usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/ec2-user/moviemasher.rb/lib/service.rb:36:in `__create_service'
/home/ec2-user/moviemasher.rb/lib/service.rb:21:in `downloader'
/home/ec2-user/moviemasher.rb/lib/asset.rb:47:in `download'
/home/ec2-user/moviemasher.rb/lib/job.rb:460:in `__cache_asset'
/home/ec2-user/moviemasher.rb/lib/job.rb:954:in `block in __process_download'
/home/ec2-user/moviemasher.rb/lib/job.rb:949:in `each'
/home/ec2-user/moviemasher.rb/lib/job.rb:949:in `__process_download'
/home/ec2-user/moviemasher.rb/lib/job.rb:339:in `process'
/home/ec2-user/moviemasher.rb/lib/moviemasher.rb:104:in `process'
/home/ec2-user/moviemasher.rb/lib/moviemasher.rb:177:in `block in process_queues'
/home/ec2-user/moviemasher.rb/lib/moviemasher.rb:172:in `each'
/home/ec2-user/moviemasher.rb/lib/moviemasher.rb:172:in `process_queues'
/home/ec2-user/moviemasher.rb/Rakefile.rb:46:in `block (2 levels) in <top (required)>'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/share/ruby/2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
/home/ec2-user/moviemasher.rb/lib/job.rb:510:in `rescue in __cache_asset'
/home/ec2-user/moviemasher.rb/lib/job.rb:457:in `__cache_asset'
/home/ec2-user/moviemasher.rb/lib/job.rb:954:in `block in __process_download'
/home/ec2-user/moviemasher.rb/lib/job.rb:949:in `each'
/home/ec2-user/moviemasher.rb/lib/job.rb:949:in `__process_download'
/home/ec2-user/moviemasher.rb/lib/job.rb:339:in `process'
/home/ec2-user/moviemasher.rb/lib/moviemasher.rb:104:in `process'
/home/ec2-user/moviemasher.rb/lib/moviemasher.rb:177:in `block in process_queues'
/home/ec2-user/moviemasher.rb/lib/moviemasher.rb:172:in `each'
/home/ec2-user/moviemasher.rb/lib/moviemasher.rb:172:in `process_queues'
/home/ec2-user/moviemasher.rb/Rakefile.rb:46:in `block (2 levels) in <top (required)>'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `call'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/task.rb:240:in `block in execute'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `each'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/task.rb:235:in `execute'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/usr/share/ruby/2.0/monitor.rb:211:in `mon_synchronize'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/task.rb:165:in `invoke'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/application.rb:150:in `invoke_task'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `each'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/application.rb:106:in `block in top_level'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/application.rb:115:in `run_with_threads'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/application.rb:100:in `top_level'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/application.rb:78:in `block in run'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/lib/rake/application.rb:75:in `run'
/usr/local/share/ruby/gems/2.0/gems/rake-10.3.2/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:23:in `load'
/usr/local/bin/rake:23:in `<main>'
uninitialized constant MovieMasher::HttpDownloadService
__callback error
posting callback https://test.shotclip.com/api/transcoder/error
callback OK response: api/transcoder/error
```

**Comment by syntropo** [comment]
Cool, thanks - that should be fixed in the push I just made...

**Comment by conor-mac-aoidh** [comment]
Thanks, no longer getting that error using the latest commit. But still no metadata that I can see - the input is the same as posted when I re-opened the issue.

**Comment by syntropo** [comment]
How are you referencing the input and metadata within the callback body? If 'job.inputs[0].metadata.title' doesn't work, you might try just 'input.metadata.title'. And you do need to reference into metadata - the entire metadata payload isn't retrievable at this time.

**Comment by conor-mac-aoidh** [comment]
I cant access the metadata using either of those keys. I've tried using `{job.inputs[0].metadata}`, `{job.inputs[0].metadata.title}`, `{input.metadata.title}' with no luck.

So in input request JSON, I have added:

```javascript
{ 
   name: 'test-bucket/audio/14b4f00195e_14b9eaf8372/original.mp3',
   type: 'audio',
   source:
   {
     type: 'https',
     host: 's3.amazonaws.com',
     path: '/test-bucket/audio/14b4f00195e_14b9eaf8372/original.mp3',
     port: 443
   },
   offset: 0,
   start: 0,
   duration: 334.9,
   length: 334.9,
   gain: 1,
   loop: 1,
   no_video: true,
   no_audio: false,
   av: 'audio'
   metadata : '{input.metadata.title}'
}
```

I've tried this for the 3 keys mentioned. I've also tried referencing it in the callback body.

**Comment by syntropo** [comment]
The metadata key itself shouldn't be specified in the input - it is a method of the Asset class that probes the file for the metadata. There is a 'metadata' test in the 010_callback_spec.rb script that seems to be passing... In it we're specifying a key value in the callback as '{job.inputs.0.metadata.title}' and it seems to be correctly evaluating to the title of the input file, as specified in its metadata. Could you share the callback's configuration?

**Comment by conor-mac-aoidh** [comment]
Oh ok, that explains a lot! I was using the bloody `inputs[0]` notation instead of `inputs.0`. Anyway, its working a charm now! Thanks for the assistance.

**Comment by syntropo** [comment]
Completely understandable - that is much more intuitive syntax, but unfortunately not yet supported.
